name: Sentiment Analysis

on:
  workflow_dispatch:
    inputs:
      docket_number:
        description: 'Docket Number'
        required: true

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install requests pandas matplotlib seaborn transformers torch

    - name: Run Sentiment Analysis
      run: |
        python sentiment_analysis.py ${{ github.event.inputs.docket_number }}

    - name: Commit and Push Image
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add *.png
        git commit -m "Add sentiment analysis image for docket ${{ github.event.inputs.docket_number }}"
        git push
